<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_sbAcIA4bEfCJh9kTxj4n4A" name="MyDiagram" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_sbAcIQ4bEfCJh9kTxj4n4A" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_sbAcIg4bEfCJh9kTxj4n4A" name="Employee lane" actor="_sbAcOw4bEfCJh9kTxj4n4A">
        <elements xmi:type="process:StartEvent" xmi:id="_sbAcIw4bEfCJh9kTxj4n4A" name="Sign Through Web" outgoing="_sbAcOA4bEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sbAcJA4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sbAcJQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sbAcJg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_sbAcJw4bEfCJh9kTxj4n4A" name="fill Sign up form" outgoing="_5lCNcA4bEfCJh9kTxj4n4A" incoming="_sbAcOA4bEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sbAcKA4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sbAcKQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sbAcKg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sbAcKw4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sbAcLA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sbAcLQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sbAcLg4bEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sbAcLw4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_sbAcMA4bEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_sbAcMQ4bEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_sbAcMg4bEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_sbAcMw4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_t5hokA4bEfCJh9kTxj4n4A" name="Sign Through Sales Team" outgoing="_1UGjwA4bEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t5hokQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t5hokg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t5hokw4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zhLNkA4bEfCJh9kTxj4n4A" name="fill Sign up form" outgoing="_64BfUA4bEfCJh9kTxj4n4A" incoming="_1UGjwA4bEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zhLNkQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zhLNkg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zhLNkw4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zhLNlA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zhLNlQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zhLNlg4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zhLNlw4bEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zhLNmA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zhLNmQ4bEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_zhLNmg4bEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zhLNmw4bEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zhLNnA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_5JBm4A4bEfCJh9kTxj4n4A" name="Gateway1" outgoing="_-GLdaw4bEfCJh9kTxj4n4A" incoming="_5lCNcA4bEfCJh9kTxj4n4A _9s-TMA4bEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4gr0gg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4gr0gQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4gr0gw4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_9bhW0A4bEfCJh9kTxj4n4A" name="Record Bonus Information" outgoing="_9s-TMA4bEfCJh9kTxj4n4A" incoming="_64BfUA4bEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_64ARMg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_64ARMQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_64A4QA4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_64A4QQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_64A4Qg4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_64A4Qw4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_64A4RQ4bEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_64A4RA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_TvRswA4cEfCJh9kTxj4n4A" name="Lane1">
        <elements xmi:type="process:Task" xmi:id="_-qRo8A4bEfCJh9kTxj4n4A" name="Collect Client Information" outgoing="_Yh1c0g4cEfCJh9kTxj4n4A" incoming="_-GLdaw4bEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-GLdYQ4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-GLdYA4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-GLdYg4bEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-GLdYw4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-GLdZA4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-GLdZQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-GLdZw4bEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-GLdZg4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-qRo-g4bEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_-qRo-w4bEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-qRo-Q4bEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-qRo_A4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Y_zyQA4cEfCJh9kTxj4n4A" name="Gateway2" outgoing="_ZSCKtw4cEfCJh9kTxj4n4A _j-LkUQ4cEfCJh9kTxj4n4A" incoming="_Yh1c0g4cEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Yh01wg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Yh01wQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Yh01ww4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_b_nLQA4cEfCJh9kTxj4n4A" name="tell client they are declined " outgoing="_g0w8UA4cEfCJh9kTxj4n4A" incoming="_ZSCKtw4cEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZSBjog4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZSBjoQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZSBjow4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZSBjpA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZSCKsA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZSCKsQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZSCKsw4cEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZSCKsg4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_b_nLSg4cEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_b_nLSw4cEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_b_nLSQ4cEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_b_nLTA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_gigusA4cEfCJh9kTxj4n4A" name="END CLIENT NOT APPROVED" incoming="_g0w8UA4cEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gihVwQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gihVwA4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gihVwg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kN2YAA4cEfCJh9kTxj4n4A" name="Decide client Transaction limt " outgoing="_mh4QJg4cEfCJh9kTxj4n4A" incoming="_j-LkUQ4cEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j-KWMg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j-KWMQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j-KWMw4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j-KWNA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j-KWNQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j-KWNg4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j-KWOA4cEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j-KWNw4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kN2_GQ4cEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_kN2_Gg4cEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kN2_GA4cEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kN2_Gw4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mzQ7EA4cEfCJh9kTxj4n4A" name="Create New client record " outgoing="_pP1EJw4cEfCJh9kTxj4n4A" incoming="_mh4QJg4cEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mh3pEg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mh3pEQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mh3pEw4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mh3pFA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mh3pFQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mh4QIA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mh4QIg4cEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mh4QIQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mzQ7Gg4cEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_mzQ7Gw4cEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mzQ7GQ4cEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mzQ7HA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_peXPYA4cEfCJh9kTxj4n4A" name="Gateway3" outgoing="_psOsQw4cEfCJh9kTxj4n4A _Q7XlQA4dEfCJh9kTxj4n4A" incoming="_pP1EJw4cEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pP1EIQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pP1EIA4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pP1EIg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rhBqsA4cEfCJh9kTxj4n4A" name="client meets with firm " outgoing="_RsKwEA4dEfCJh9kTxj4n4A" incoming="_psOsQw4cEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_psOFMg4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_psOFMQ4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_psOFMw4cEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_psOFNA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_psOFNQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_psOFNg4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_psOFOA4cEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_psOFNw4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rhBqug4cEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_rhBquw4cEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rhBquQ4cEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rhBqvA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_RN5fsA4dEfCJh9kTxj4n4A" name="Gateway4" outgoing="_YzHkow4dEfCJh9kTxj4n4A" incoming="_Q7XlQA4dEfCJh9kTxj4n4A _RsKwEA4dEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q7W-MQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q7W-MA4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q7W-Mg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZPO44A4dEfCJh9kTxj4n4A" name="create account" outgoing="_jWsREw4dEfCJh9kTxj4n4A" incoming="_YzHkow4dEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YzG9kg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YzG9kQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YzG9kw4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YzG9lA4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YzG9lQ4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YzG9lg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YzG9mA4dEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YzG9lw4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZPPf-Q4dEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_ZPPf-g4dEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZPPf-A4dEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZPPf-w4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_jlpTEA4dEfCJh9kTxj4n4A" name="Gateway5" outgoing="_ofAOsA4dEfCJh9kTxj4n4A _sdHqEA4dEfCJh9kTxj4n4A" incoming="_jWsREw4dEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWrqAg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWrqAQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWrqAw4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rgrP8A4dEfCJh9kTxj4n4A" name="Create HIN" outgoing="_r75MWA4dEfCJh9kTxj4n4A" incoming="_ofAOsA4dEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j74BwQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j74BwA4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j74Bwg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j74Bww4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j74BxA4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j74BxQ4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j74Bxw4dEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j74Bxg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rgrP-g4dEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_rgrP-w4dEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rgrP-Q4dEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rgrP_A4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sIAVsA4dEfCJh9kTxj4n4A" name="Gateway6" outgoing="_vaTsmA4gEfCJh9kTxj4n4A" incoming="_r75MWA4dEfCJh9kTxj4n4A _sdHqEA4dEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r75MUg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r75MUQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r75MUw4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4WUssA4dEfCJh9kTxj4n4A" name="Fill Transfer instruction form " outgoing="_CMgHoA4eEfCJh9kTxj4n4A" incoming="_y1wAFw4dEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y1vZAg4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y1vZAQ4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y1vZAw4dEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_y1vZBA4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_y1wAEA4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_y1wAEQ4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_y1wAEw4dEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_y1wAEg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4WUsug4dEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_4WUsuw4dEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4WUsuQ4dEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4WUsvA4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_CjmZAA4eEfCJh9kTxj4n4A" name="contact existing broker " outgoing="_FNFjzA4eEfCJh9kTxj4n4A" incoming="_CMgHoA4eEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CMfgkg4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CMfgkQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CMfgkw4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_CMfglA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_CMfglQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CMfglg4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_CMfgmA4eEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_CMfglw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_CjnAGQ4eEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_CjnAGg4eEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_CjnAGA4eEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_CjnAGw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HGhxoA4eEfCJh9kTxj4n4A" name="Transfer Assets" outgoing="_KWKWZw4eEfCJh9kTxj4n4A" incoming="_FNFjzA4eEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FNFjwg4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FNFjwQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FNFjww4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FNFjxA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FNFjxQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FNFjxg4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FNFjyA4eEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FNFjxw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HGiYtQ4eEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_HGiYtg4eEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HGiYtA4eEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HGiYtw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Klpj4A4eEfCJh9kTxj4n4A" name="Gateway7" outgoing="_O2cDrA4eEfCJh9kTxj4n4A" incoming="_KWKWZw4eEfCJh9kTxj4n4A _xN__Kw4dEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KWKWYQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KWKWYA4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KWKWYg4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PwEaUA4eEfCJh9kTxj4n4A" name="Transfer Cash" outgoing="_ZHqb0A4eEfCJh9kTxj4n4A" incoming="_O2cDrA4eEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_O2cDog4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_O2cDoQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_O2cDow4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_O2cDpA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_O2cDpQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_O2cDpg4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_O2cDqA4eEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_O2cDpw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PwEaWg4eEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_PwEaWw4eEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PwEaWQ4eEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PwEaXA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ZYwL0A4eEfCJh9kTxj4n4A" name="Gateway8" outgoing="_eX_F8A4eEfCJh9kTxj4n4A _k8bqaw4eEfCJh9kTxj4n4A" incoming="_ZHqb0A4eEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZHp0wg4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZHp0wQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZHp0ww4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_f0uwwA4eEfCJh9kTxj4n4A" name="EnableClient trading" outgoing="_2fKPYA4gEfCJh9kTxj4n4A" incoming="_tpXTYA4gEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eX-e4g4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eX-e4Q4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eX-e4w4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eX-e5A4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eX-e5Q4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eX-e5g4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eX-e6A4eEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eX-e5w4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_f0vX2Q4eEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_f0vX2g4eEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_f0vX2A4eEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_f0vX2w4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_oBq9AA4eEfCJh9kTxj4n4A" name="re evaluate daily limit" outgoing="_rpyoVA4gEfCJh9kTxj4n4A" incoming="_k8bqaw4eEfCJh9kTxj4n4A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_k8bqYQ4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_k8bqYA4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_k8bqYg4eEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_k8bqYw4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_k8bqZA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_k8bqZQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_k8bqZw4eEfCJh9kTxj4n4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_k8bqZg4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_oBq9Cg4eEfCJh9kTxj4n4A">
            <targetForm xmi:type="expression:Expression" xmi:id="_oBq9Cw4eEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_oBq9CQ4eEfCJh9kTxj4n4A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_oBq9DA4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sEyiQA4gEfCJh9kTxj4n4A" name="Gateway9" outgoing="_tpXTYA4gEfCJh9kTxj4n4A" incoming="_rpyoVA4gEfCJh9kTxj4n4A _eX_F8A4eEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rpxaMg4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rpxaMQ4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rpxaMw4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_vtr7kA4gEfCJh9kTxj4n4A" name="Gateway10" outgoing="_xN__Kw4dEfCJh9kTxj4n4A _y1wAFw4dEfCJh9kTxj4n4A" incoming="_vaTsmA4gEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vaTskg4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vaTskQ4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vaTskw4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_1Bsy4A4gEfCJh9kTxj4n4A" name="End1" incoming="_2fKPYA4gEfCJh9kTxj4n4A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1BtZ8Q4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1BtZ8A4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1BtZ8g4gEfCJh9kTxj4n4A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_sbAcNA4bEfCJh9kTxj4n4A">
        <targetForm xmi:type="expression:Expression" xmi:id="_sbAcNQ4bEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_sbAcNg4bEfCJh9kTxj4n4A">
        <targetForm xmi:type="expression:Expression" xmi:id="_sbAcNw4bEfCJh9kTxj4n4A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sbAcOA4bEfCJh9kTxj4n4A" target="_sbAcJw4bEfCJh9kTxj4n4A" source="_sbAcIw4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sbAcOQ4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_sbAcOg4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1UGjwA4bEfCJh9kTxj4n4A" target="_zhLNkA4bEfCJh9kTxj4n4A" source="_t5hokA4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1UHK0A4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_1UHK0Q4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5lCNcA4bEfCJh9kTxj4n4A" target="_5JBm4A4bEfCJh9kTxj4n4A" source="_sbAcJw4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5lCNcQ4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_5lCNcg4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_64BfUA4bEfCJh9kTxj4n4A" target="_9bhW0A4bEfCJh9kTxj4n4A" source="_zhLNkA4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_64BfUQ4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_64BfUg4bEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9s-TMA4bEfCJh9kTxj4n4A" target="_5JBm4A4bEfCJh9kTxj4n4A" source="_9bhW0A4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9s-6QA4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_9s-6QQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-GLdaw4bEfCJh9kTxj4n4A" target="_-qRo8A4bEfCJh9kTxj4n4A" source="_5JBm4A4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-GLdbA4bEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_-GLdbQ4bEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Yh1c0g4cEfCJh9kTxj4n4A" target="_Y_zyQA4cEfCJh9kTxj4n4A" source="_-qRo8A4bEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Yh1c0w4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Yh1c1A4cEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZSCKtw4cEfCJh9kTxj4n4A" name="Client Not approved" target="_b_nLQA4cEfCJh9kTxj4n4A" source="_Y_zyQA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZSCKuA4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZSCxwA4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g0w8UA4cEfCJh9kTxj4n4A" target="_gigusA4cEfCJh9kTxj4n4A" source="_b_nLQA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g0w8UQ4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_g0w8Ug4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j-LkUQ4cEfCJh9kTxj4n4A" target="_kN2YAA4cEfCJh9kTxj4n4A" source="_Y_zyQA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j-LkUg4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_j-LkUw4cEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mh4QJg4cEfCJh9kTxj4n4A" target="_mzQ7EA4cEfCJh9kTxj4n4A" source="_kN2YAA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mh4QJw4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_mh4QKA4cEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pP1EJw4cEfCJh9kTxj4n4A" target="_peXPYA4cEfCJh9kTxj4n4A" source="_mzQ7EA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pP1EKA4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_pP1EKQ4cEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_psOsQw4cEfCJh9kTxj4n4A" name="Client assest more than a mil" target="_rhBqsA4cEfCJh9kTxj4n4A" source="_peXPYA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_psOsRA4cEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_psOsRQ4cEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Q7XlQA4dEfCJh9kTxj4n4A" name="client assest less than a mil" target="_RN5fsA4dEfCJh9kTxj4n4A" source="_peXPYA4cEfCJh9kTxj4n4A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Q7XlQQ4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Q7XlQg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RsKwEA4dEfCJh9kTxj4n4A" target="_RN5fsA4dEfCJh9kTxj4n4A" source="_rhBqsA4cEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RsKwEQ4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_RsKwEg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YzHkow4dEfCJh9kTxj4n4A" target="_ZPO44A4dEfCJh9kTxj4n4A" source="_RN5fsA4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YzHkpA4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_YzHkpQ4dEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jWsREw4dEfCJh9kTxj4n4A" target="_jlpTEA4dEfCJh9kTxj4n4A" source="_ZPO44A4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jWsRFA4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_jWsRFQ4dEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ofAOsA4dEfCJh9kTxj4n4A" name="client does not have a HIN" target="_rgrP8A4dEfCJh9kTxj4n4A" source="_jlpTEA4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ofAOsQ4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ofAOsg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r75MWA4dEfCJh9kTxj4n4A" target="_sIAVsA4dEfCJh9kTxj4n4A" source="_rgrP8A4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r75MWQ4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_r75MWg4dEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sdHqEA4dEfCJh9kTxj4n4A" name="Client has a HIN " target="_sIAVsA4dEfCJh9kTxj4n4A" source="_jlpTEA4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sdHqEQ4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_sdHqEg4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xN__Kw4dEfCJh9kTxj4n4A" name="Client Does not have stocks to transfer" target="_Klpj4A4eEfCJh9kTxj4n4A" source="_vtr7kA4gEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xN__LA4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_xN__LQ4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y1wAFw4dEfCJh9kTxj4n4A" name="Client does have stocks to transfer" target="_4WUssA4dEfCJh9kTxj4n4A" source="_vtr7kA4gEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y1wAGA4dEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_y1wAGQ4dEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CMgHoA4eEfCJh9kTxj4n4A" target="_CjmZAA4eEfCJh9kTxj4n4A" source="_4WUssA4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CMgHoQ4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_CMgHog4eEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FNFjzA4eEfCJh9kTxj4n4A" target="_HGhxoA4eEfCJh9kTxj4n4A" source="_CjmZAA4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FNFjzQ4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_FNFjzg4eEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KWKWZw4eEfCJh9kTxj4n4A" target="_Klpj4A4eEfCJh9kTxj4n4A" source="_HGhxoA4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KWKWaA4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_KWKWaQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O2cDrA4eEfCJh9kTxj4n4A" target="_PwEaUA4eEfCJh9kTxj4n4A" source="_Klpj4A4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O2cqsA4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_O2cqsQ4eEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZHqb0A4eEfCJh9kTxj4n4A" target="_ZYwL0A4eEfCJh9kTxj4n4A" source="_PwEaUA4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZHqb0Q4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZHqb0g4eEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eX_F8A4eEfCJh9kTxj4n4A" name="Daily Transaction limit is less than current cash" target="_sEyiQA4gEfCJh9kTxj4n4A" source="_ZYwL0A4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eX_F8Q4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_eX_F8g4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k8bqaw4eEfCJh9kTxj4n4A" name="daily transac lim more than current cash" target="_oBq9AA4eEfCJh9kTxj4n4A" source="_ZYwL0A4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k8bqbA4eEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_k8bqbQ4eEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rpyoVA4gEfCJh9kTxj4n4A" target="_sEyiQA4gEfCJh9kTxj4n4A" source="_oBq9AA4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rpyoVQ4gEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_rpyoVg4gEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tpXTYA4gEfCJh9kTxj4n4A" target="_f0uwwA4eEfCJh9kTxj4n4A" source="_sEyiQA4gEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tpXTYQ4gEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tpXTYg4gEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vaTsmA4gEfCJh9kTxj4n4A" target="_vtr7kA4gEfCJh9kTxj4n4A" source="_sIAVsA4dEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vaTsmQ4gEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_vaTsmg4gEfCJh9kTxj4n4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2fKPYA4gEfCJh9kTxj4n4A" target="_1Bsy4A4gEfCJh9kTxj4n4A" source="_f0uwwA4eEfCJh9kTxj4n4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2fKPYQ4gEfCJh9kTxj4n4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_2fKPYg4gEfCJh9kTxj4n4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_sbAcOw4bEfCJh9kTxj4n4A" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_sbAcPA4bEfCJh9kTxj4n4A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sbAcPQ4bEfCJh9kTxj4n4A">
        <name xmi:type="expression:Expression" xmi:id="_sbAcPg4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sbAcPw4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sbAcQA4bEfCJh9kTxj4n4A">
        <name xmi:type="expression:Expression" xmi:id="_sbAcQQ4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sbAcQg4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sbAcQw4bEfCJh9kTxj4n4A">
        <name xmi:type="expression:Expression" xmi:id="_sbAcRA4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sbAcRQ4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sbAcRg4bEfCJh9kTxj4n4A">
        <name xmi:type="expression:Expression" xmi:id="_sbAcRw4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sbAcSA4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sbBDMA4bEfCJh9kTxj4n4A">
        <name xmi:type="expression:Expression" xmi:id="_sbBDMQ4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sbBDMg4bEfCJh9kTxj4n4A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_sbBDMw4bEfCJh9kTxj4n4A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_sbBDNA4bEfCJh9kTxj4n4A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_sbBDNQ4bEfCJh9kTxj4n4A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_sbBDNg4bEfCJh9kTxj4n4A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_sbBDNw4bEfCJh9kTxj4n4A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_sbBDOA4bEfCJh9kTxj4n4A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_sbBDOQ4bEfCJh9kTxj4n4A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_sbBDOg4bEfCJh9kTxj4n4A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_sbBDOw4bEfCJh9kTxj4n4A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_sbBDPA4bEfCJh9kTxj4n4A" type="Process" element="_sbAcIA4bEfCJh9kTxj4n4A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_sbBDPQ4bEfCJh9kTxj4n4A" type="2007" element="_sbAcIQ4bEfCJh9kTxj4n4A">
      <children xmi:type="notation:DecorationNode" xmi:id="_sbBDPg4bEfCJh9kTxj4n4A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_sbBDPw4bEfCJh9kTxj4n4A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_sbBDQA4bEfCJh9kTxj4n4A" type="3007" element="_sbAcIg4bEfCJh9kTxj4n4A">
          <children xmi:type="notation:DecorationNode" xmi:id="_sbBDQQ4bEfCJh9kTxj4n4A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_sbBDQg4bEfCJh9kTxj4n4A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_sbBDQw4bEfCJh9kTxj4n4A" type="3005" element="_sbAcJw4bEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sbBDRA4bEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sbBDRQ4bEfCJh9kTxj4n4A" x="194" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sbBDRg4bEfCJh9kTxj4n4A" type="3002" element="_sbAcIw4bEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sbBDRw4bEfCJh9kTxj4n4A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sbBDSA4bEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sbBDSQ4bEfCJh9kTxj4n4A" x="80" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_t5i2sA4bEfCJh9kTxj4n4A" type="3002" element="_t5hokA4bEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_t5i2sQ4bEfCJh9kTxj4n4A" type="5024" element="_t5hokA4bEfCJh9kTxj4n4A">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_t5i2sg4bEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t5i2sw4bEfCJh9kTxj4n4A" x="80" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zhL0oA4bEfCJh9kTxj4n4A" type="3005" element="_zhLNkA4bEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zhL0oQ4bEfCJh9kTxj4n4A" type="5005" element="_zhLNkA4bEfCJh9kTxj4n4A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zhL0og4bEfCJh9kTxj4n4A" x="175" y="179" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5JCN8A4bEfCJh9kTxj4n4A" type="3008" element="_5JBm4A4bEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5JCN8g4bEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5JCN8w4bEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5JCN8Q4bEfCJh9kTxj4n4A" x="536" y="143" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9bh96A4bEfCJh9kTxj4n4A" type="3027" element="_9bhW0A4bEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9bh96g4bEfCJh9kTxj4n4A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9bh96Q4bEfCJh9kTxj4n4A" x="323" y="185" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_sbBDSg4bEfCJh9kTxj4n4A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_sbBDSw4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_sbBDTA4bEfCJh9kTxj4n4A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_sbBDTQ4bEfCJh9kTxj4n4A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sbBDTg4bEfCJh9kTxj4n4A" x="48" y="10" width="1297" height="408"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_TvST0A4cEfCJh9kTxj4n4A" type="3007" element="_TvRswA4cEfCJh9kTxj4n4A">
          <children xmi:type="notation:DecorationNode" xmi:id="_TvS64A4cEfCJh9kTxj4n4A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TvS64Q4cEfCJh9kTxj4n4A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_-qSQAA4bEfCJh9kTxj4n4A" type="3005" element="_-qRo8A4bEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-qSQAg4bEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-qSQAQ4bEfCJh9kTxj4n4A" x="45" y="75" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y_zyRA4cEfCJh9kTxj4n4A" type="3008" element="_Y_zyQA4cEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y_0ZUA4cEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Y_0ZUQ4cEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y_zyRQ4cEfCJh9kTxj4n4A" x="270" y="83" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b_nyUA4cEfCJh9kTxj4n4A" type="3005" element="_b_nLQA4cEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_b_nyUg4cEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b_nyUQ4cEfCJh9kTxj4n4A" x="372" y="176" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gih80A4cEfCJh9kTxj4n4A" type="3003" element="_gigusA4cEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gih80g4cEfCJh9kTxj4n4A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gih80w4cEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gih80Q4cEfCJh9kTxj4n4A" x="555" y="189"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kN2_HA4cEfCJh9kTxj4n4A" type="3005" element="_kN2YAA4cEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kN2_Hg4cEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kN2_HQ4cEfCJh9kTxj4n4A" x="377" y="57" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mzQ7HQ4cEfCJh9kTxj4n4A" type="3005" element="_mzQ7EA4cEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mzQ7Hw4cEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mzQ7Hg4cEfCJh9kTxj4n4A" x="615" y="56" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_peXPZA4cEfCJh9kTxj4n4A" type="3008" element="_peXPYA4cEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_peXPZg4cEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_peXPZw4cEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_peXPZQ4cEfCJh9kTxj4n4A" x="831" y="65" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rhBqvQ4cEfCJh9kTxj4n4A" type="3005" element="_rhBqsA4cEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rhCRwA4cEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rhBqvg4cEfCJh9kTxj4n4A" x="1087" y="16" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RN5ftA4dEfCJh9kTxj4n4A" type="3008" element="_RN5fsA4dEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_RN5ftg4dEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RN5ftw4dEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RN5ftQ4dEfCJh9kTxj4n4A" x="1255" y="107" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZPPf_A4dEfCJh9kTxj4n4A" type="3005" element="_ZPO44A4dEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZPPf_g4dEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZPPf_Q4dEfCJh9kTxj4n4A" x="1364" y="86" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jlpTFA4dEfCJh9kTxj4n4A" type="3008" element="_jlpTEA4dEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jlpTFg4dEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jlpTFw4dEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jlpTFQ4dEfCJh9kTxj4n4A" x="1542" y="97" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rgrP_Q4dEfCJh9kTxj4n4A" type="3005" element="_rgrP8A4dEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rgr3AA4dEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rgrP_g4dEfCJh9kTxj4n4A" x="1714" y="48" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sIAVtA4dEfCJh9kTxj4n4A" type="3008" element="_sIAVsA4dEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sIAVtg4dEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sIAVtw4dEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sIAVtQ4dEfCJh9kTxj4n4A" x="1864" y="106" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4WUsvQ4dEfCJh9kTxj4n4A" type="3005" element="_4WUssA4dEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4WVTwA4dEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4WUsvg4dEfCJh9kTxj4n4A" x="2079" y="233" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CjnAHA4eEfCJh9kTxj4n4A" type="3005" element="_CjmZAA4eEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_CjnAHg4eEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CjnAHQ4eEfCJh9kTxj4n4A" x="2257" y="235" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HGiYuA4eEfCJh9kTxj4n4A" type="3005" element="_HGhxoA4eEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HGiYug4eEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HGiYuQ4eEfCJh9kTxj4n4A" x="2436" y="240" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KlqK8w4eEfCJh9kTxj4n4A" type="3008" element="_Klpj4A4eEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_KlqK9Q4eEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_KlqK9g4eEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KlqK9A4eEfCJh9kTxj4n4A" x="2464" y="89" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PwEaXQ4eEfCJh9kTxj4n4A" type="3005" element="_PwEaUA4eEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PwEaXw4eEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PwEaXg4eEfCJh9kTxj4n4A" x="2548" y="87" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZYwL1A4eEfCJh9kTxj4n4A" type="3008" element="_ZYwL0A4eEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZYwL1g4eEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZYwL1w4eEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZYwL1Q4eEfCJh9kTxj4n4A" x="2709" y="87" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f0vX3A4eEfCJh9kTxj4n4A" type="3005" element="_f0uwwA4eEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f0vX3g4eEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f0vX3Q4eEfCJh9kTxj4n4A" x="3158" y="106" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oBq9DQ4eEfCJh9kTxj4n4A" type="3005" element="_oBq9AA4eEfCJh9kTxj4n4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oBq9Dw4eEfCJh9kTxj4n4A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oBq9Dg4eEfCJh9kTxj4n4A" x="2816" y="305" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sEyiRA4gEfCJh9kTxj4n4A" type="3008" element="_sEyiQA4gEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sEyiRg4gEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sEyiRw4gEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sEyiRQ4gEfCJh9kTxj4n4A" x="3021" y="156" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vtsiog4gEfCJh9kTxj4n4A" type="3008" element="_vtr7kA4gEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vtsipA4gEfCJh9kTxj4n4A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vtsipQ4gEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vtsiow4gEfCJh9kTxj4n4A" x="1942" y="107" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1BtZ8w4gEfCJh9kTxj4n4A" type="3003" element="_1Bsy4A4gEfCJh9kTxj4n4A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1BtZ9Q4gEfCJh9kTxj4n4A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1BtZ9g4gEfCJh9kTxj4n4A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1BtZ9A4gEfCJh9kTxj4n4A" x="3293" y="123"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TvST0Q4cEfCJh9kTxj4n4A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TvST0g4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TvST0w4cEfCJh9kTxj4n4A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TvS64g4cEfCJh9kTxj4n4A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TvST1A4cEfCJh9kTxj4n4A" x="23" y="408" width="1447" height="446"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_sbBDTw4bEfCJh9kTxj4n4A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_sbBDUA4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_sbBDUQ4bEfCJh9kTxj4n4A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_sbBDUg4bEfCJh9kTxj4n4A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sbBDUw4bEfCJh9kTxj4n4A" width="3420" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_sbBDVA4bEfCJh9kTxj4n4A"/>
    <edges xmi:type="notation:Connector" xmi:id="_sbBDVQ4bEfCJh9kTxj4n4A" type="4001" element="_sbAcOA4bEfCJh9kTxj4n4A" source="_sbBDRg4bEfCJh9kTxj4n4A" target="_sbBDQw4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sbBDVg4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sbBDVw4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sbBDWA4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sbBDWQ4bEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1UHx4A4bEfCJh9kTxj4n4A" type="4001" element="_1UGjwA4bEfCJh9kTxj4n4A" source="_t5i2sA4bEfCJh9kTxj4n4A" target="_zhL0oA4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1UIY8A4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1UIY8Q4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1UHx4Q4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1UHx4g4bEfCJh9kTxj4n4A" points="[-1, -11, -126, -14]$[65, 5, -60, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1UJnEA4bEfCJh9kTxj4n4A" id="(1.0,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5lC0gA4bEfCJh9kTxj4n4A" type="4001" element="_5lCNcA4bEfCJh9kTxj4n4A" source="_sbBDQw4bEfCJh9kTxj4n4A" target="_5JCN8A4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5lC0gw4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5lC0hA4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5lC0gQ4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5lC0gg4bEfCJh9kTxj4n4A" points="[0, 0, -111, -68]$[116, 85, 5, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5lDbkA4bEfCJh9kTxj4n4A" id="(1.0,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_64BfUw4bEfCJh9kTxj4n4A" type="4001" element="_64BfUA4bEfCJh9kTxj4n4A" source="_zhL0oA4bEfCJh9kTxj4n4A" target="_9bh96A4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_64BfVg4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_64BfVw4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_64BfVA4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_64BfVQ4bEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9s_hUA4bEfCJh9kTxj4n4A" type="4001" element="_9s-TMA4bEfCJh9kTxj4n4A" source="_9bh96A4bEfCJh9kTxj4n4A" target="_5JCN8A4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9s_hUw4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9s_hVA4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9s_hUQ4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9s_hUg4bEfCJh9kTxj4n4A" points="[0, 0, -114, 49]$[116, -69, 2, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9tAIYA4bEfCJh9kTxj4n4A" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-GMEcA4bEfCJh9kTxj4n4A" type="4001" element="_-GLdaw4bEfCJh9kTxj4n4A" source="_5JCN8A4bEfCJh9kTxj4n4A" target="_-qSQAA4bEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-GMEcw4bEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-GMEdA4bEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-GMEcQ4bEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-GMEcg4bEfCJh9kTxj4n4A" points="[0, 22, 427, -379]$[0, 167, 427, -234]$[-40, 167, 387, -234]$[-40, 200, 387, -201]$[-401, 200, 26, -201]$[-401, 376, 26, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Yh1c1Q4cEfCJh9kTxj4n4A" type="4001" element="_Yh1c0g4cEfCJh9kTxj4n4A" source="_-qSQAA4bEfCJh9kTxj4n4A" target="_Y_zyRA4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Yh1c2A4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Yh1c2Q4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Yh1c1g4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Yh1c1w4cEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZSCxwQ4cEfCJh9kTxj4n4A" type="4001" element="_ZSCKtw4cEfCJh9kTxj4n4A" source="_Y_zyRA4cEfCJh9kTxj4n4A" target="_b_nyUA4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZSCxxA4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZSCxxQ4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZSCxwg4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZSCxww4cEfCJh9kTxj4n4A" points="[-9, 5, -141, -80]$[-9, 97, -141, 12]$[72, 97, -60, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bDp5UA4cEfCJh9kTxj4n4A" id="(0.6976744186046512,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g0xjYA4cEfCJh9kTxj4n4A" type="4001" element="_g0w8UA4cEfCJh9kTxj4n4A" source="_b_nyUA4cEfCJh9kTxj4n4A" target="_gih80A4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g0xjYw4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g0xjZA4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g0xjYQ4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g0xjYg4cEfCJh9kTxj4n4A" points="[0, 0, -70, -12]$[66, 26, -4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g0yKcA4cEfCJh9kTxj4n4A" id="(1.0,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j-LkVA4cEfCJh9kTxj4n4A" type="4001" element="_j-LkUQ4cEfCJh9kTxj4n4A" source="_Y_zyRA4cEfCJh9kTxj4n4A" target="_kN2_HA4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j-LkVw4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j-LkWA4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j-LkVQ4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j-LkVg4cEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mh4QKQ4cEfCJh9kTxj4n4A" type="4001" element="_mh4QJg4cEfCJh9kTxj4n4A" source="_kN2_HA4cEfCJh9kTxj4n4A" target="_mzQ7HQ4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mh4QLA4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mh4QLQ4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mh4QKg4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mh4QKw4cEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pP1EKg4cEfCJh9kTxj4n4A" type="4001" element="_pP1EJw4cEfCJh9kTxj4n4A" source="_mzQ7HQ4cEfCJh9kTxj4n4A" target="_peXPZA4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pP1ELQ4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pP1ELg4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pP1EKw4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pP1ELA4cEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_psOsRg4cEfCJh9kTxj4n4A" type="4001" element="_psOsQw4cEfCJh9kTxj4n4A" source="_peXPZA4cEfCJh9kTxj4n4A" target="_rhBqvQ4cEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_psOsSQ4cEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_psOsSg4cEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_psOsRw4cEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_psOsSA4cEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Q7XlQw4dEfCJh9kTxj4n4A" type="4001" element="_Q7XlQA4dEfCJh9kTxj4n4A" source="_peXPZA4cEfCJh9kTxj4n4A" target="_RN5ftA4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Q7XlRg4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Q7XlRw4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Q7XlRA4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Q7XlRQ4dEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YB7_UA4dEfCJh9kTxj4n4A" id="(0.5116279069767442,0.9069767441860465)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XmSlIA4dEfCJh9kTxj4n4A" id="(0.046511627906976744,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RsLXIA4dEfCJh9kTxj4n4A" type="4001" element="_RsKwEA4dEfCJh9kTxj4n4A" source="_rhBqvQ4cEfCJh9kTxj4n4A" target="_RN5ftA4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RsLXIw4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RsLXJA4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RsLXIQ4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RsLXIg4dEfCJh9kTxj4n4A" points="[0, 0, -70, -105]$[70, 98, 0, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RsL-MA4dEfCJh9kTxj4n4A" id="(1.0,0.4)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RsL-MQ4dEfCJh9kTxj4n4A" id="(0.5116279069767442,0.18604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YzHkpg4dEfCJh9kTxj4n4A" type="4001" element="_YzHkow4dEfCJh9kTxj4n4A" source="_RN5ftA4dEfCJh9kTxj4n4A" target="_ZPPf_A4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YzHkqQ4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YzHkqg4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YzHkpw4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YzHkqA4dEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jWsRFg4dEfCJh9kTxj4n4A" type="4001" element="_jWsREw4dEfCJh9kTxj4n4A" source="_ZPPf_A4dEfCJh9kTxj4n4A" target="_jlpTFA4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jWsRGQ4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jWsRGg4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jWsRFw4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jWsRGA4dEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ofAOsw4dEfCJh9kTxj4n4A" type="4001" element="_ofAOsA4dEfCJh9kTxj4n4A" source="_jlpTFA4dEfCJh9kTxj4n4A" target="_rgrP_Q4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ofA1wg4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ofA1ww4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ofA1wA4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ofA1wQ4dEfCJh9kTxj4n4A" points="[-13, -3, -189, -40]$[226, 35, 50, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ofBc0A4dEfCJh9kTxj4n4A" id="(1.0,0.8372093023255814)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r75zYA4dEfCJh9kTxj4n4A" type="4001" element="_r75MWA4dEfCJh9kTxj4n4A" source="_rgrP_Q4dEfCJh9kTxj4n4A" target="_sIAVtA4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r75zYw4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r75zZA4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r75zYQ4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r75zYg4dEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sdL7gA4dEfCJh9kTxj4n4A" type="4001" element="_sdHqEA4dEfCJh9kTxj4n4A" source="_jlpTFA4dEfCJh9kTxj4n4A" target="_sIAVtA4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sdL7gw4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sdL7hA4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sdL7gQ4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sdL7gg4dEfCJh9kTxj4n4A" points="[-8, -4, -308, -1]$[295, -19, -5, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sdMikA4dEfCJh9kTxj4n4A" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xN__Lg4dEfCJh9kTxj4n4A" type="4001" element="_xN__Kw4dEfCJh9kTxj4n4A" source="_vtsiog4gEfCJh9kTxj4n4A" target="_KlqK8w4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xOAmMA4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xOAmMQ4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xN__Lw4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xN__MA4dEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w3HBwA4gEfCJh9kTxj4n4A" id="(0.7441860465116279,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y1wAGg4dEfCJh9kTxj4n4A" type="4001" element="_y1wAFw4dEfCJh9kTxj4n4A" source="_vtsiog4gEfCJh9kTxj4n4A" target="_4WUsvQ4dEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y1wnIg4dEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y1wnIw4dEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y1wnIA4dEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y1wnIQ4dEfCJh9kTxj4n4A" points="[0, 22, -116, -90]$[0, 119, -116, 7]$[66, 119, -50, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ySL4oA4gEfCJh9kTxj4n4A" id="(0.37209302325581395,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CMgHow4eEfCJh9kTxj4n4A" type="4001" element="_CMgHoA4eEfCJh9kTxj4n4A" source="_4WUsvQ4dEfCJh9kTxj4n4A" target="_CjnAHA4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CMgHpg4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CMgHpw4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CMgHpA4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CMgHpQ4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FNFjzw4eEfCJh9kTxj4n4A" type="4001" element="_FNFjzA4eEfCJh9kTxj4n4A" source="_CjnAHA4eEfCJh9kTxj4n4A" target="_HGiYuA4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FNGK0A4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FNGK0Q4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FNFj0A4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FNFj0Q4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KWKWag4eEfCJh9kTxj4n4A" type="4001" element="_KWKWZw4eEfCJh9kTxj4n4A" source="_HGiYuA4eEfCJh9kTxj4n4A" target="_KlqK8w4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KWKWbQ4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KWKWbg4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KWKWaw4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KWKWbA4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O2cqsg4eEfCJh9kTxj4n4A" type="4001" element="_O2cDrA4eEfCJh9kTxj4n4A" source="_KlqK8w4eEfCJh9kTxj4n4A" target="_PwEaXQ4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O2cqtQ4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O2cqtg4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O2cqsw4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O2cqtA4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZHqb0w4eEfCJh9kTxj4n4A" type="4001" element="_ZHqb0A4eEfCJh9kTxj4n4A" source="_PwEaXQ4eEfCJh9kTxj4n4A" target="_ZYwL1A4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZHqb1g4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZHqb1w4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZHqb1A4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZHqb1Q4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eX_F8w4eEfCJh9kTxj4n4A" type="4001" element="_eX_F8A4eEfCJh9kTxj4n4A" source="_ZYwL1A4eEfCJh9kTxj4n4A" target="_sEyiRA4gEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eX_F9g4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eX_F9w4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eX_F9A4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eX_F9Q4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k8bqbg4eEfCJh9kTxj4n4A" type="4001" element="_k8bqaw4eEfCJh9kTxj4n4A" source="_ZYwL1A4eEfCJh9kTxj4n4A" target="_oBq9DQ4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k8bqcQ4eEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k8bqcg4eEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k8bqbw4eEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k8bqcA4eEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lsIB8A4eEfCJh9kTxj4n4A" id="(0.37209302325581395,0.8604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rpyoVw4gEfCJh9kTxj4n4A" type="4001" element="_rpyoVA4gEfCJh9kTxj4n4A" source="_oBq9DQ4eEfCJh9kTxj4n4A" target="_sEyiRA4gEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rpyoWg4gEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rpyoWw4gEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rpyoWA4gEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rpyoWQ4gEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tpX6cA4gEfCJh9kTxj4n4A" type="4001" element="_tpXTYA4gEfCJh9kTxj4n4A" source="_sEyiRA4gEfCJh9kTxj4n4A" target="_f0vX3A4eEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tpX6cw4gEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tpX6dA4gEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tpX6cQ4gEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tpX6cg4gEfCJh9kTxj4n4A" points="[-12, -18, -46, 48]$[18, -64, -16, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tpYhgA4gEfCJh9kTxj4n4A" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tpYhgQ4gEfCJh9kTxj4n4A" id="(0.13333333333333333,0.6166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vaUToA4gEfCJh9kTxj4n4A" type="4001" element="_vaTsmA4gEfCJh9kTxj4n4A" source="_sIAVtA4dEfCJh9kTxj4n4A" target="_vtsiog4gEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vaUTow4gEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vaUTpA4gEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vaUToQ4gEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vaUTog4gEfCJh9kTxj4n4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2fKPYw4gEfCJh9kTxj4n4A" type="4001" element="_2fKPYA4gEfCJh9kTxj4n4A" source="_f0vX3A4eEfCJh9kTxj4n4A" target="_1BtZ8w4gEfCJh9kTxj4n4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2fKPZg4gEfCJh9kTxj4n4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2fKPZw4gEfCJh9kTxj4n4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2fKPZA4gEfCJh9kTxj4n4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2fKPZQ4gEfCJh9kTxj4n4A" points="[0, 4, -41, 0]$[44, 3, 3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2fK2cA4gEfCJh9kTxj4n4A" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2fK2cQ4gEfCJh9kTxj4n4A" id="(0.8666666666666667,0.4666666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
